# Generated by Django 4.0.3 on 2022-03-24 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='list',
            name='collaborators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
